#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# install.sh — SDD Agent Viewer installer
#
# What it does:
#   1. Creates ~/.local/bin/viewer  (global launcher, points to this repo)
#   2. Patches ~/.config/opencode/opencode.json with:
#      a) Auto-launch rule (say "arranca el viewer" in opencode)
#      b) VIEWER INTEGRATION block in sdd-orchestrator agent prompt
#         so every SDD phase notifies the viewer in real time.
#         Works whether or not you have Gentleman Skills installed.
#
# Requirements:
#   - Python 3.10+
#   - opencode installed (https://opencode.ai)
#   - ~/.local/bin must be in your $PATH
#
# Usage:
#   git clone https://github.com/gentleman-org/agent_viewer.git
#   cd agent_viewer
#   bash install.sh
# ─────────────────────────────────────────────────────────────

set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
VIEWER_BIN="$BIN_DIR/viewer"
OPENCODE_JSON="$HOME/.config/opencode/opencode.json"

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${CYAN}╔══════════════════════════════════════╗${NC}"
echo -e "${CYAN}║      SDD Agent Viewer — Installer    ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════╝${NC}"
echo ""

# ── 1. Check Python ──────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
    echo -e "${RED}✗ Python 3 not found. Install it first.${NC}"
    exit 1
fi
PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
echo -e "${GREEN}✓ Python $PY_VER found${NC}"

# ── 2. Create ~/.local/bin if missing ────────────────────────
mkdir -p "$BIN_DIR"

# ── 3. Write the global viewer wrapper ───────────────────────
cat > "$VIEWER_BIN" << WRAPPER
#!/bin/sh
# SDD Agent Viewer — global launcher
# Auto-generated by install.sh — do not edit manually.
# Re-run install.sh after moving the repo.
exec python3 "$REPO_DIR/viewer.py" "\$@"
WRAPPER

chmod +x "$VIEWER_BIN"
echo -e "${GREEN}✓ Global command installed: $VIEWER_BIN${NC}"

# ── 4. Check ~/.local/bin is in PATH ────────────────────────
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo ""
    echo -e "${YELLOW}⚠ $BIN_DIR is not in your PATH.${NC}"
    echo -e "  Add this line to your ~/.zshrc or ~/.bashrc:"
    echo -e "  ${CYAN}export PATH=\"\$HOME/.local/bin:\$PATH\"${NC}"
    echo ""
fi

# ── 5. Patch opencode.json ────────────────────────────────────
if [ ! -f "$OPENCODE_JSON" ]; then
    echo -e "${YELLOW}⚠ opencode.json not found at $OPENCODE_JSON${NC}"
    echo -e "  Skipping opencode integration patch."
    echo -e "  Run opencode once to generate the config, then re-run install.sh."
    echo ""
else
    python3 - "$OPENCODE_JSON" << 'PYEOF'
import sys, json, os

config_path = sys.argv[1]

with open(config_path, "r") as f:
    config = json.load(f)

changed = False

# ── 5a. Auto-launch rule in top-level instructions ────────────
AUTO_LAUNCH = (
    'VIEWER AUTO-LAUNCH RULE:\n'
    'If the user says anything like "abre el viewer", "abrir viewer", "open viewer", '
    '"lanza el viewer", "arranca el viewer", "start viewer", "inicia el viewer", '
    'or any similar variation requesting to open/launch the visual dashboard — '
    'immediately run Bash: '
    '`_OWNER=$(ps -o ppid= -p $PPID | tr -d \' \'); viewer --owner-pid $_OWNER > /tmp/viewer.log 2>&1 &` '
    'then confirm with one line: "✅ Viewer lanzado — http://localhost:<port>" '
    '(read port from /tmp/sdd_viewer.port if available, otherwise just say "abriendo en background"). '
    'Do NOT ask for confirmation before launching. Do NOT open a new terminal. Just run it.'
)

instructions = config.get("instructions", [])
if isinstance(instructions, str):
    instructions = [instructions]

if not any("VIEWER AUTO-LAUNCH RULE" in str(i) for i in instructions):
    instructions.insert(0, AUTO_LAUNCH)
    config["instructions"] = instructions
    changed = True
    print("  → Auto-launch rule added to instructions.")
else:
    print("  → Auto-launch rule already present, skipping.")

# ── 5b. VIEWER INTEGRATION block in sdd-orchestrator prompt ──
VIEWER_INTEGRATION = (
    "\nVIEWER INTEGRATION (optional, silent-fail):\n"
    "If /tmp/sdd_viewer.port exists, a visual dashboard may be running.\n"
    "Before delegating each phase via Task, notify the viewer by running Bash:\n"
    "  _VPORT=$(cat /tmp/sdd_viewer.port 2>/dev/null || echo \"\"); "
    "if [ -n \"$_VPORT\" ]; then curl -sf -X POST \"http://localhost:$_VPORT/state\" "
    "-H \"Content-Type: application/json\" "
    "-d '{\"orchestrator\":\"delegating\",\"current_agent\":\"AGENT\","
    "\"agent_state\":\"working\",\"current_task\":\"TASK\"}' || true; fi\n\n"
    "After each Task returns, notify done:\n"
    "  _VPORT=$(cat /tmp/sdd_viewer.port 2>/dev/null || echo \"\"); "
    "if [ -n \"$_VPORT\" ]; then curl -sf -X POST \"http://localhost:$_VPORT/state\" "
    "-H \"Content-Type: application/json\" "
    "-d '{\"orchestrator\":\"reviewing\",\"current_agent\":\"AGENT\","
    "\"agent_state\":\"done\",\"current_task\":\"\"}' || true; fi\n\n"
    "When all phases are complete, set idle:\n"
    "  _VPORT=$(cat /tmp/sdd_viewer.port 2>/dev/null || echo \"\"); "
    "if [ -n \"$_VPORT\" ]; then curl -sf -X POST \"http://localhost:$_VPORT/state\" "
    "-H \"Content-Type: application/json\" "
    "-d '{\"orchestrator\":\"idle\",\"current_agent\":null,"
    "\"agent_state\":\"idle\",\"current_task\":\"\"}' || true; fi\n\n"
    "Replace AGENT with the skill name (explore/propose/spec/design/tasks/apply/verify/archive) "
    "and TASK with a short description.\n"
    "All curl calls are fire-and-forget (|| true). Never block on viewer availability."
)

agents = config.get("agent", {})
orch = agents.get("sdd-orchestrator", {})
prompt = orch.get("prompt", "")

if "VIEWER INTEGRATION" not in prompt:
    if prompt:
        # Append to existing orchestrator prompt
        orch["prompt"] = prompt.rstrip() + "\n" + VIEWER_INTEGRATION
        agents["sdd-orchestrator"] = orch
        config["agent"] = agents
        changed = True
        print("  → VIEWER INTEGRATION block added to sdd-orchestrator prompt.")
    else:
        # No sdd-orchestrator yet — create a minimal one
        agents["sdd-orchestrator"] = {
            "mode": "all",
            "description": "SDD Orchestrator",
            "prompt": VIEWER_INTEGRATION.strip()
        }
        config["agent"] = agents
        changed = True
        print("  → sdd-orchestrator agent created with VIEWER INTEGRATION block.")
else:
    print("  → VIEWER INTEGRATION already present in sdd-orchestrator, skipping.")

# ── Write back ────────────────────────────────────────────────
if changed:
    backup_path = config_path + ".bak"
    os.rename(config_path, backup_path)
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)
    print(f"  → opencode.json saved. Backup at {backup_path}")
else:
    print("  → No changes needed.")
PYEOF

    echo -e "${GREEN}✓ opencode.json patched${NC}"
fi

# ── 6. Done ──────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         Installation complete!       ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${CYAN}viewer${NC}               → start the dashboard"
echo -e "  ${CYAN}viewer --help${NC}        → show options"
echo -e "  ${CYAN}python3 viewer_client.py test${NC}  → run full demo"
echo ""
echo -e "  In opencode, just say: ${CYAN}\"arranca el viewer\"${NC}"
echo ""
